# Generated by Django 3.2.13 on 2026-08-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('person', models.CharField(max_length=200)),
                ('rfc_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ng_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tf_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gi_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('person', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('site_name', models.CharField(blank=True, max_length=200)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('person', models.CharField(max_length=200)),
                ('site_name', models.CharField(blank=True, max_length=200)),
                ('material_description', models.CharField(max_length=200)),
                ('material_size', models.CharField(blank=True, max_length=100)),
                ('issued_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('installed_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('person', models.CharField(max_length=200)),
                ('material_category', models.CharField(blank=True, max_length=200)),
                ('material_description', models.CharField(max_length=200)),
                ('material_size', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('issued_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('site_name', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
    ]
